# -*- coding: utf-8 -*-
"""pos_tagger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVtH6bSESCLSqXu9H7xsF35-V0Yjgr1b
"""

!pip install sklearn-crfsuite
!pip install sklearn-crfsuite
import os
os.kill(os.getpid(), 9)  # force kernel restart
"""
pos_tagger.py — Urdu CRF-based POS Tagger
==========================================
T5 deliverable: CRF model trained on UD Urdu Treebank
Target accuracy: ≥ 90 %

Pipeline
--------
1. Download UD Urdu Treebank (UDTB) via datasets / direct URL
2. Extract (word, UPOS-tag) pairs from CoNLL-U files
3. Extract character n-gram + context features
4. Train sklearn-crfsuite CRF model
5. Evaluate on test split → report accuracy
6. Save model to urdu_pos_crf.pkl for reuse

Usage
-----
>>> tagger = UrduPOSTagger.load("urdu_pos_crf.pkl")
>>> tagger.tag("میں کتاب پڑھتا ہوں".split())
[('میں', 'PRON'), ('کتاب', 'NOUN'), ('پڑھتا', 'VERB'), ('ہوں', 'AUX')]

Author : NuTech AI-23 | F23607023
"""

import os
import re
import pickle
import urllib.request
from pathlib import Path
from typing import Sequence

# ---------------------------------------------------------------------------
# Optional heavy deps — imported lazily so the module itself always loads
# ---------------------------------------------------------------------------
def _require(pkg: str, pip_name: str = ""):
    import importlib
    try:
        return importlib.import_module(pkg)
    except ImportError:
        pn = pip_name or pkg
        raise ImportError(
            f"Package '{pn}' is required. Install with:  pip install {pn}"
        )


# ---------------------------------------------------------------------------
# CoNLL-U helpers
# ---------------------------------------------------------------------------

def read_conllu(path: str) -> list[list[tuple[str, str]]]:
    """
    Parse a CoNLL-U file.
    Returns list of sentences, each sentence = list of (word, upos) tuples.
    Multi-word tokens (lines with '-') and empty nodes ('.' ids) are skipped.
    """
    sentences, current = [], []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith("#"):
                continue
            if line == "":
                if current:
                    sentences.append(current)
                    current = []
                continue
            cols = line.split("\t")
            if len(cols) < 4:
                continue
            tok_id = cols[0]
            if "-" in tok_id or "." in tok_id:   # skip MWT / empty nodes
                continue
            word = cols[1]
            upos = cols[3]
            if upos == "_":
                continue
            current.append((word, upos))
    if current:
        sentences.append(current)
    return sentences


# ---------------------------------------------------------------------------
# Feature extraction
# ---------------------------------------------------------------------------

def _char_ngrams(word: str, n: int) -> list[str]:
    return [word[i:i+n] for i in range(len(word) - n + 1)]


def word_features(sent: list[str], i: int) -> dict:
    """
    Feature dict for word at position i in sentence.
    Uses current word, ±2 context words, prefixes/suffixes.
    """
    word = sent[i]
    feats = {
        "bias":         1.0,
        "word":         word,
        "word.lower":   word.lower(),
        "word[-3:]":    word[-3:],
        "word[-2:]":    word[-2:],
        "word[:3]":     word[:3],
        "word[:2]":     word[:2],
        "word.len":     len(word),
        "word.isdigit": word.isdigit(),
    }

    # character bigrams & trigrams
    for bg in _char_ngrams(word, 2):
        feats[f"word.bg={bg}"] = True
    for tg in _char_ngrams(word, 3):
        feats[f"word.tg={tg}"] = True

    # context: -2, -1, +1, +2
    for offset, label in [(-2, "w-2"), (-1, "w-1"), (1, "w+1"), (2, "w+2")]:
        idx = i + offset
        if 0 <= idx < len(sent):
            ctx = sent[idx]
            feats.update({
                f"{label}":       ctx,
                f"{label}[-3:]":  ctx[-3:],
                f"{label}[:3]":   ctx[:3],
            })
        else:
            feats[f"{label}.BOS_EOS"] = True

    # sentence-boundary flags
    if i == 0:
        feats["BOS"] = True
    if i == len(sent) - 1:
        feats["EOS"] = True

    return feats


def sent_to_features(sent: list[str]) -> list[dict]:
    return [word_features(sent, i) for i in range(len(sent))]

def sent_to_labels(sent: list[tuple[str, str]]) -> list[str]:
    return [tag for _, tag in sent]

def sent_to_tokens(sent: list[tuple[str, str]]) -> list[str]:
    return [w for w, _ in sent]


# ---------------------------------------------------------------------------
# Download UD Urdu Treebank
# ---------------------------------------------------------------------------

UDTB_BASE = "https://raw.githubusercontent.com/UniversalDependencies/UD_Urdu-UDTB/master"
UDTB_FILES = {
    "train": "ur_udtb-ud-train.conllu",
    "dev":   "ur_udtb-ud-dev.conllu",
    "test":  "ur_udtb-ud-test.conllu",
}

def download_udtb(dest_dir: str = "udtb_data") -> dict[str, str]:
    """
    Download the three CoNLL-U splits of UD Urdu UDTB.
    Returns dict {split: local_path}.
    """
    os.makedirs(dest_dir, exist_ok=True)
    paths = {}
    for split, fname in UDTB_FILES.items():
        local = os.path.join(dest_dir, fname)
        if not os.path.exists(local):
            url = f"{UDTB_BASE}/{fname}"
            print(f"Downloading {split} split → {local}")
            urllib.request.urlretrieve(url, local)
        else:
            print(f"[cache] {split} split already at {local}")
        paths[split] = local
    return paths


# ---------------------------------------------------------------------------
# Main tagger class
# ---------------------------------------------------------------------------

class UrduPOSTagger:
    """
    CRF-based Urdu POS tagger trained on UD Urdu Treebank.

    Training
    --------
    >>> tagger = UrduPOSTagger()
    >>> tagger.train("udtb_data/ur_udtb-ud-train.conllu",
    ...              "udtb_data/ur_udtb-ud-dev.conllu")
    >>> tagger.evaluate("udtb_data/ur_udtb-ud-test.conllu")
    >>> tagger.save("urdu_pos_crf.pkl")

    Inference
    ---------
    >>> tagger = UrduPOSTagger.load("urdu_pos_crf.pkl")
    >>> tagger.tag("میں کتاب پڑھتا ہوں".split())
    """

    def __init__(self):
        self.model = None
        self.labels: list[str] = []

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def train(
        self,
        train_path: str,
        dev_path: str   = "",
        *,
        max_iterations: int = 200,
        c1: float = 0.1,
        c2: float = 0.1,
    ):
        crfsuite = _require("sklearn_crfsuite", "sklearn-crfsuite")
        CRF = crfsuite.CRF

        print("Reading training data …")
        train_sents = read_conllu(train_path)
        print(f"  {len(train_sents):,} training sentences")

        X_train = [sent_to_features(sent_to_tokens(s)) for s in train_sents]
        y_train = [sent_to_labels(s)                   for s in train_sents]

        self.labels = sorted({tag for s in train_sents for _, tag in s})

        print(f"Labels ({len(self.labels)}): {self.labels}")
        print("Training CRF …")

        self.model = CRF(
            algorithm="lbfgs",
            c1=c1,
            c2=c2,
            max_iterations=max_iterations,
            all_possible_transitions=True,
        )
        self.model.fit(X_train, y_train)
        print("Training complete.")

        if dev_path:
            print("\n--- Dev evaluation ---")
            self.evaluate(dev_path)

    # ------------------------------------------------------------------
    # Evaluation
    # ------------------------------------------------------------------

    def evaluate(self, conllu_path: str) -> dict:
        metrics = _require("sklearn_crfsuite.metrics", "sklearn-crfsuite")
        flat_f1 = _require("sklearn_crfsuite.metrics", "sklearn-crfsuite")

        from sklearn_crfsuite import metrics as crf_metrics
        from sklearn.metrics import accuracy_score

        sents = read_conllu(conllu_path)
        X = [sent_to_features(sent_to_tokens(s)) for s in sents]
        y_true = [sent_to_labels(s)              for s in sents]
        y_pred = self.model.predict(X)

        # flat accuracy
        flat_true = [t for seq in y_true for t in seq]
        flat_pred = [t for seq in y_pred for t in seq]
        acc = accuracy_score(flat_true, flat_pred)

        print(f"Token accuracy : {acc*100:.2f}%")
        print()
        print(crf_metrics.flat_classification_report(
            y_true, y_pred, labels=self.labels, digits=4
        ))

        return {"accuracy": acc, "y_true": flat_true, "y_pred": flat_pred}

    # ------------------------------------------------------------------
    # Inference
    # ------------------------------------------------------------------

    def tag(self, tokens: list[str]) -> list[tuple[str, str]]:
        """POS-tag a pre-tokenized list of Urdu tokens."""
        if self.model is None:
            raise RuntimeError("Model not trained/loaded. Call train() or load().")
        feats  = sent_to_features(tokens)
        tags   = self.model.predict([feats])[0]
        return list(zip(tokens, tags))

    def tag_sentence(self, sentence: str) -> list[tuple[str, str]]:
        """Convenience wrapper: splits on whitespace then tags."""
        return self.tag(sentence.split())

    # ------------------------------------------------------------------
    # Persist
    # ------------------------------------------------------------------

    def save(self, path: str = "urdu_pos_crf.pkl"):
        with open(path, "wb") as f:
            pickle.dump({"model": self.model, "labels": self.labels}, f)
        print(f"Model saved → {path}")

    @classmethod
    def load(cls, path: str = "urdu_pos_crf.pkl") -> "UrduPOSTagger":
        inst = cls()
        with open(path, "rb") as f:
            data = pickle.load(f)
        inst.model  = data["model"]
        inst.labels = data["labels"]
        print(f"Model loaded ← {path}")
        return inst


# ---------------------------------------------------------------------------
# Quick smoke-test (run after training)
# ---------------------------------------------------------------------------

DEMO_SENTENCES = [
    "میں کتاب پڑھتا ہوں",
    "وہ بازار گئی",
    "استاد نے سوال پوچھا",
    "بچے کھیل رہے ہیں",
    "یہ گھر بہت بڑا ہے",
]

def smoke_test(tagger: UrduPOSTagger):
    print("\n=== Smoke Test ===")
    for sent in DEMO_SENTENCES:
        tagged = tagger.tag_sentence(sent)
        formatted = "  ".join(f"{w}/{t}" for w, t in tagged)
        print(f"  {formatted}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    paths  = download_udtb()
    tagger = UrduPOSTagger()
    tagger.train(paths["train"], paths["dev"])
    print("\n=== Test Set Evaluation ===")
    tagger.evaluate(paths["test"])
    tagger.save("urdu_pos_crf.pkl")
    smoke_test(tagger)